### ISSUE TITLE
Issue with Timestamps

### ISSUE THREAD

**Issue by stormfish-sci** [yaqwsx/SensorStreamer#2]
First off, this is a great app!  Thank you for authoring and releasing it.

I have experienced some issues with timestamps which I hope you might be able to shed some light.

Sometimes the timestamps work as expected, other times I get very strange values.  Here is an example:

`"accelerometer": {
      "timestamp": 45147364669817,
      "value": [
        9.456436,
        -0.035888672,
        2.9001007
      ]
    }`

Interpreting this value as a unix_ms timestamp converts to 3400-08-30 22:37:49.  

`"accelerometer": {
      "timestamp": 1955431849769,
      "value": [
        -9.272186,
        0.19621277,
        2.9766693
      ]
    }`
 
This one coverts to 2031-12-19 07:30:49, better but still not right.

Am I interpreting these values incorrectly or have I found a bug?

Thanks again!

**Comment by sebandraos** [comment]
In the [readme.md](https://github.com/yaqwsx/SensorStreamer/blob/master/readme.md) it notes that the timestamps are in nano seconds so you could try dividing by 1,000,000 before converting. These values then become very small so I would assume they consider 0 to be the time the device was last turned on. From the [Android doc](https://developer.android.com/reference/android/hardware/SensorEvent) they seem to use this data to find time deltas between data rather than time and date at which the data was taken.

From [readme.md](https://github.com/yaqwsx/SensorStreamer/blob/master/readme.md):

_The packets contain a JSON object as the top level entity. This object contains a field for each sensor. Each sensor supplies two values:_

_`timestamp` (in form of nano seconds)_

**Comment by stormfish-sci** [comment]
Thank you for that helpful response.  Your description explains a number of my observations.  I'll try to parse the time data as you describe and report back if that resolves my issue.

**Comment by yaqwsx** [comment]
sebandraos: Thank you for your answer. It is exactly as you say.

Is it OK to close this issue?

**Comment by sebandraos** [comment]
@yaqwsx I was waiting for stromfish-sci to confirm but if the answer is correct I think that definitely closes the issue

**Comment by stormfish-sci** [comment]
@sebandraos, thank you for your patience and the reminder to close the loop on this.

I have checked my telemetry logs based on your input.  I concur that the timestamps are consistent with your description.  When running with the "High period (200 ms) options, and interpreting the sensor timestamps as nanoseconds, I consistently see 196 ms between samples.

However, the reference time/epoch upon which these timestamps are based remains unclear.  In a few instances, the timestamp 0.0 would equate to 184 days prior to the time of reading.  I am not sure what the significance of that might be; I reboot my device about every 7 days due to popup reminders it presents.

Regardless, I'm not worried about the epoch issue.  Now that I am able to make effective use of the timestamp deltas I am in good shape.

Thanks for your help and the great software!
